pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Mustafa') {
            steps {
                echo 'Mustafa Tahran'
            }
        }
        stage('passwd') {
            steps {
                sh 'cat /etc/passwd'
            }
        }
    }
}